---

- name: Configure MariaDB Master Node
  hosts: database_master
  become: yes # Run tasks as root user
  vars:
    mariadb_root_password: "your_root_password"
    replication_user: "replica_user"
    replication_password: "replica_password"
    bind_address: "0.0.0.0"  # You can restrict this to a specific IP address for security.
    server_id: "1"  # Unique server_id for the master node

  tasks:
    - name: Install MariaDB server
      dnf:
        name: mariadb105-server
        state: present

    - name: Ensure Mariadb service is started and enabled
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Configure Mariadb for replication (Master config)
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: "^{{ item.key }}"
        line: "{{ item.key }} = {{ item.value }}"
        create: yes
      with_items:
        - { key: "server-id", value: "{{ server_id }}" }
        - { key: "log-bin", value: "mysql-bin" }
        - { key: "bind-address", value: "{{ bind_address }}" }
        - { key: "log-slave-updates", value: "1" }
        - { key: "gtid-mode", value: "ON" }
        - { key: "enforce-gtid-consistency", value: "ON" }
        - { key: "binlog-format", value: "ROW" }

    - name: Install pip3 if not present
      dnf:
        name: python3-pip
        state: present

    - name: Install PyMySQL for MySQL support
      pip:
        name: PyMySQL
        state: present
        executable: pip3

    - name: Create replication user
      mysql_user:
        name: "{{ replication_user }}"
        password: "{{ replication_password }}"
        priv: "*.*:REPLICATION SLAVE"
        state: present
        host: '%'
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        login_host: localhost

    - name: Get the master log file and position
      mysql_db:
        name: information_schema
        state: query
        sql: "SHOW MASTER STATUS;"
      register: master_status
      no_log: true

    - name: Print master status for debugging (optional)
      debug:
        msg: "Master Log File: {{ master_status.query_result[0].File }}, Position: {{ master_status.query_result[0].Position }}"

    - name: Store the master log file and position to a file for later use
      copy:
        content: |
          Master_Log_File: {{ master_status.query_result[0].File }}
          Position: {{ master_status.query_result[0].Position }}
        dest: /tmp/master_status.txt

    - name: Restart MariaDB to apply configuration changes
      service:
        name: mariadb
        state: restarted

